### ISSUE TITLE
Unhandled Exception with MissingPluginException in Production

### ISSUE THREAD

**Issue by mys10gan** [joutvhu/open_file_plus#15]
### Description
When using `open_file_plus` in the production build of my Flutter app, I encounter a `MissingPluginException` error. This issue does not occur in debug mode. The error message is:
```[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method open_file on channel open_file_plus)```

### Steps to Reproduce
1. Add `open_file_plus` to `pubspec.yaml`
2. Use `OpenFile.open(filePath)` in the app
3. Build the app in production mode using `flutter build apk`
4. Install and run the app on an Android device

#### Exact code that runs this

```dart
Future<void> saveFile(Uint8List bytes, String filename) async {
    Directory? directory;
    // Request permissions if necessary
    if (Platform.isAndroid) {
      directory = await getExternalStorageDirectory();
    } else if (Platform.isIOS) {
      directory = await getApplicationDocumentsDirectory();
    }
    final filePath = '${directory!.path}/$filename';
    final file = File(filePath);

    logger.i("Saving file to $filePath");

    // Write the file
    await file.writeAsBytes(bytes);
    // open the file
    dynamic result = await OpenFile.open(filePath);
    logger.i("File saved successfully");
    if (result.type != ResultType.done) {
      logger.e("Error opening file: $result");
    }

    return;
  }
```

### Expected vs. Actual Behavior
**Expected:** The file should open without any errors.
**Actual:** The app throws a `MissingPluginException` when trying to open a file.

### Environment
- Flutter Version: 3.19.5
- open_file_plus Version: 3.4.1+1
- OS: Android 14
- Device: Samsung Galaxy S23

#### Dependencies
```yaml
dependencies:
  flutter:
    sdk: flutter

  wifi_scan: ^0.4.0+1
  shimmer: ^3.0.0
  location: ^6.0.1
  http: ^1.2.1
  flutter_inappwebview: ^6.0.0
  share_plus: ^8.0.2
  package_info_plus: ^7.0.0
  connectivity_plus: ^6.0.2
  logger: ^2.2.0
  app_settings: ^5.1.1
  wifi_iot: ^0.3.18
  network_info_plus: ^5.0.2
  uni_links: ^0.5.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  open_file_plus: ^3.4.1+1
  ```

#### Flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

### Additional Context
The issue only appears in the production build. Debug builds work as expected. I have attempted `flutter clean` and re-running `flutter pub get`, but the issue persists.

Please let me know if there's any more information I can provide to help resolve this issue. Thank you!
