### ISSUE TITLE
Bug : Error with open_file_plus plugin on Flutter - Compilation Failure (cannot find symbol PluginRegistry.Registrar) in flutter 3.29

### ISSUE THREAD

**Issue by rajain23** [joutvhu/open_file_plus#25]
Plugin.java:66: error: cannot find symbol
    public static void registerWith(PluginRegistry.Registrar registrar) {
                                                  ^
  symbol:   class Registrar
  location: interface PluginRegistry
1 error

**Comment by OYTAdmin** [comment]
Same here.

**Comment by kururu-abdo** [comment]
check this answer

[https://github.com/joutvhu/open_file_plus/issues/22#issuecomment-2658675273](url)

**Comment by FrasKc** [comment]
> check this answer
> 
> [https://github.com/joutvhu/open_file_plus/issues/22#issuecomment-2658675273](url)

Your link don't work. Same issue here on flutter 3.29

**Comment by Quintonvv** [comment]
The issue im getting:

error: cannot find symbol
public static void registerWith(PluginRegistry.Registrar registrar) {
                                                                       ^
  symbol:   class Registrar
  location: interface PluginRegistry
1 error

FAILURE: Build failed with an exception.

**Comment by kururu-abdo** [comment]
> > check this answer
> > [https://github.com/joutvhu/open_file_plus/issues/22#issuecomment-2658675273](url)
> 
> Your link don't work. Same issue here on flutter 3.29

it works for me  i am using Flutter 3.29 too

check android project may be you should update gradle files

**Comment by SanthoshKothoju** [comment]
same issue

**Comment by kh1amirhamza** [comment]
Just add this dependency into your ```pubspec.yaml``` file  instead of current one untill author update the package!

```yaml
dependencies:
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus.git
```

**Comment by ali-eryushion** [comment]
same issue here

**Comment by inehalbabu** [comment]
> open_file_plus:
>     git:
>       url: https://github.com/postflow/open_file_plus.git

Thanks it is working for me 😊

**Comment by iamnabink** [comment]
You can use this:

```
dependencies:
  open_file_plus:
    git:
      url: https://github.com/iamnabink/another_open_file.git
```
